name: Terraform CI/CD
on: 
  push:
    branches: [main]
  workflow_dispatch:    
jobs:
  build-artifact:
    strategy:
      matrix:
        environment: [dev, stg, prod]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/CI-CD_Terraform
          aws-region: us-east-1


      - name: Terraform init
        working-directory: terraform
        run: terraform init -lock-timeout=300s


      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select ${{matrix.environment}} || terraform workspace new ${{matrix.environment}}

      - name: Terraform Validate 
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan-${{matrix.environment}}

      - name: upload Artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 2
          name: tfplan-${{matrix.environment}}
          path: terraform/tfplan-${{matrix.environment}}


  deploy-artifact-dev:
    needs: build-artifact
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-dev
          path: terraform

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/CI-CD_Terraform
          aws-region: us-east-1
      
      - name: Terraform Init 
        working-directory: terraform
        run: terraform init

      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan-dev

      - name: Terraform + CD/CD
        run: echo "Bhummmmmm! Terraform + CI/CD, Dev Successfully Worked."

    


  deploy-artifact-stg:
    needs: 
      - build-artifact
      - deploy-artifact-dev
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: stg
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-stg
          path: terraform

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/CI-CD_Terraform
          aws-region: us-east-1
      
      - name: Terraform Init 
        working-directory: terraform
        run: terraform init

      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select stg || terraform workspace new stg

      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan-stg

      - name: Terraform + CD/CD
        run: echo "Bhummmmmm! Terraform + CI/CD, Staging Successfully Worked."



  deploy-artifact-prod:
    needs: 
      - build-artifact
      - deploy-artifact-stg
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-prod
          path: terraform

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::954976311612:role/CI-CD_Terraform
          aws-region: us-east-1
      
      - name: Terraform Init 
        working-directory: terraform
        run: terraform init

      - name: Terraform create & select workspace
        working-directory: terraform
        run: |
          terraform workspace select prod || terraform workspace new prod

      - name: Terraform apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan-prod

      - name: Terraform + CD/CD
        run: echo "Bhummmmmm! Terraform + CI/CD, Production Successfully Worked."

    

